# Generated by Django 5.2.5 on 2025-08-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Activities",
                "db_table": "activite",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("accounting_account", models.BigIntegerField(blank=True, null=True)),
                ("accounting_chapter", models.BigIntegerField(blank=True, null=True)),
                ("accounting_key", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "banque",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "direction",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Employee Statuses",
                "db_table": "statut",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeneralDirection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "directiongeneral",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Origin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100)),
                (
                    "smig_hours_for_leave_allowance",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "origines",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="PayrollMotif",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("employee_subject_to_its", models.BooleanField(default=True)),
                ("employee_subject_to_cnss", models.BooleanField(default=True)),
                ("employee_subject_to_cnam", models.BooleanField(default=True)),
                ("declaration_subject_to_its", models.BooleanField(default=True)),
                ("declaration_subject_to_cnss", models.BooleanField(default=True)),
                ("declaration_subject_to_cnam", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "motif",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "poste",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="core.direction",
                    ),
                ),
            ],
            options={
                "db_table": "departement",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="direction",
            name="general_direction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directions",
                to="core.generaldirection",
            ),
        ),
    ]
