# Generated by Django 5.2.5 on 2025-08-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryGrade",
            fields=[
                (
                    "category",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=22)),
                ("category_name", models.CharField(max_length=10)),
                ("level", models.IntegerField()),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_grades",
                        to="core.employeestatus",
                    ),
                ),
            ],
            options={
                "db_table": "grillesalairebase",
                "ordering": ["level", "category"],
            },
        ),
        migrations.CreateModel(
            name="HousingGrid",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("marital_status", models.CharField(max_length=1)),
                ("children_count", models.IntegerField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                (
                    "salary_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housing_allowances",
                        to="core.salarygrade",
                    ),
                ),
            ],
            options={
                "db_table": "grillelogement",
                "ordering": ["salary_grade", "marital_status", "children_count"],
                "unique_together": {
                    ("salary_grade", "marital_status", "children_count")
                },
            },
        ),
    ]
