# Generated by Django 5.2.5 on 2025-08-14 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Employment Contract"),
                            ("ID_CARD", "Identity Card"),
                            ("PASSPORT", "Passport"),
                            ("DIPLOMA", "Diploma/Certificate"),
                            ("MEDICAL", "Medical Certificate"),
                            ("RESUME", "Resume/CV"),
                            ("REFERENCE", "Reference Letter"),
                            ("PHOTO", "Employee Photo"),
                            ("OTHER", "Other Document"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("document_name", models.CharField(max_length=500)),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                ("file_content", models.BinaryField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "Document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("period", models.DateField()),
                ("start_date", models.DateField()),
                ("planned_return", models.DateField()),
                ("actual_return", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Leave"),
                            ("SICK", "Sick Leave"),
                            ("MATERNITY", "Maternity Leave"),
                            ("PATERNITY", "Paternity Leave"),
                            ("COMPASSIONATE", "Compassionate Leave"),
                            ("UNPAID", "Unpaid Leave"),
                            ("OTHER", "Other"),
                        ],
                        default="ANNUAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "conges",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("child_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("parent_type", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "enfants",
                "ordering": ["child_name"],
                "unique_together": {("employee", "child_name", "birth_date")},
            },
        ),
        migrations.CreateModel(
            name="Diploma",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("diploma_name", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("graduation_date", models.DateField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("HIGH_SCHOOL", "High School"),
                            ("DIPLOMA", "Diploma"),
                            ("BACHELOR", "Bachelor's Degree"),
                            ("MASTER", "Master's Degree"),
                            ("DOCTORATE", "Doctorate/PhD"),
                            ("CERTIFICATE", "Professional Certificate"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=200)),
                (
                    "gpa_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("honors", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diplomas",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "diplome",
                "ordering": ["-graduation_date"],
                "unique_together": {
                    ("employee", "diploma_name", "institution", "graduation_date")
                },
            },
        ),
    ]
