# Generated by Django 5.2.5 on 2025-08-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_document_leave_child_diploma"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollElement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=500)),
                ("abbreviation", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("G", "Gain"), ("D", "Deduction")], max_length=1
                    ),
                ),
                ("has_ceiling", models.BooleanField(default=False)),
                ("is_cumulative", models.BooleanField(default=False)),
                ("affects_its", models.BooleanField(default=False)),
                ("affects_cnss", models.BooleanField(default=False)),
                ("affects_cnam", models.BooleanField(default=False)),
                ("is_benefit_in_kind", models.BooleanField(default=False)),
                ("auto_base_calculation", models.BooleanField(default=False)),
                ("auto_quantity_calculation", models.BooleanField(default=False)),
                ("accounting_account", models.BigIntegerField(default=0)),
                ("accounting_chapter", models.BigIntegerField(default=0)),
                ("accounting_key", models.CharField(blank=True, max_length=10)),
                ("deduction_from", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Payroll Element",
                "verbose_name_plural": "Payroll Elements",
                "db_table": "rubrique",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="PayrollElementFormula",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "section",
                    models.CharField(
                        choices=[("B", "Base"), ("N", "Number")], max_length=1
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("O", "Operator"),
                            ("N", "Number"),
                            ("F", "Function"),
                            ("R", "Rubrique Reference"),
                        ],
                        max_length=1,
                    ),
                ),
                ("text_value", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "numeric_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                (
                    "payroll_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="core.payrollelement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Element Formula",
                "verbose_name_plural": "Payroll Element Formulas",
                "db_table": "rubriqueformule",
                "ordering": ["payroll_element", "section", "id"],
            },
        ),
    ]
