# Generated by Django 5.2.5 on 2025-08-14 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_payroll_elements"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkWeek",
            fields=[
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_week_start", models.BooleanField(default=False)),
                ("is_week_end", models.BooleanField(default=False)),
                ("is_weekend", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "semainetravail",
                "ordering": [
                    models.Case(
                        models.When(day="MONDAY", then=models.Value(1)),
                        models.When(day="TUESDAY", then=models.Value(2)),
                        models.When(day="WEDNESDAY", then=models.Value(3)),
                        models.When(day="THURSDAY", then=models.Value(4)),
                        models.When(day="FRIDAY", then=models.Value(5)),
                        models.When(day="SATURDAY", then=models.Value(6)),
                        models.When(day="SUNDAY", then=models.Value(7)),
                        output_field=models.IntegerField(),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeClockData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                (
                    "punch_type",
                    models.CharField(
                        blank=True, choices=[("I", "IN"), ("O", "OUT")], max_length=1
                    ),
                ),
                ("is_imported", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeclock_data",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "donneespointeuse",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DailyWork",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("period", models.DateField()),
                ("work_date", models.DateField()),
                (
                    "day_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "night_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "meal_allowance_count",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "distance_allowance_count",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("holiday_100_percent", models.BooleanField(default=False)),
                ("holiday_50_percent", models.BooleanField(default=False)),
                ("external_site", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_work_records",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "jour",
                "ordering": ["-work_date"],
                "unique_together": {("employee", "work_date")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyOvertime",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("period", models.DateField()),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                (
                    "overtime_115",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "overtime_140",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "overtime_150",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "overtime_200",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "meal_allowance_count",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "distance_allowance_count",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=22,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_overtime",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "weekot",
                "ordering": ["-week_start"],
                "unique_together": {("employee", "week_start")},
            },
        ),
    ]
