# Generated by Django 5.2.5 on 2025-08-14 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_system_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payroll",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("period", models.DateField()),
                ("category", models.CharField(blank=True, max_length=20)),
                (
                    "contract_hours_month",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "gross_taxable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "gross_non_taxable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "worked_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                (
                    "cnss_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "cnam_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "its_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "its_tranche1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "its_tranche2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "its_tranche3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "rcnss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "rcnam",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "rits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "cnss_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "cnam_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "avnat_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "gross_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "net_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "cumulative_taxable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "cumulative_non_taxable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "cumulative_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                ("net_in_words", models.TextField(blank=True)),
                ("period_in_words", models.CharField(blank=True, max_length=100)),
                ("bank_name", models.CharField(blank=True, max_length=50)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("payment_mode", models.CharField(blank=True, max_length=50)),
                ("is_domiciled", models.BooleanField(default=False)),
                ("position_name", models.CharField(blank=True, max_length=100)),
                ("department_name", models.CharField(blank=True, max_length=100)),
                ("direction_name", models.CharField(blank=True, max_length=100)),
                (
                    "general_direction_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("payroll_from_date", models.DateField(blank=True, null=True)),
                ("payroll_to_date", models.DateField(blank=True, null=True)),
                ("last_departure_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "fte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50)),
                ("classification", models.CharField(blank=True, max_length=200)),
                ("activity", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payrolls",
                        to="core.employee",
                    ),
                ),
                (
                    "motif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payrolls",
                        to="core.payrollmotif",
                    ),
                ),
                (
                    "parameters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payrolls",
                        to="core.systemparameters",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processed_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payrolls",
                "db_table": "paie",
                "ordering": ["-period", "employee__last_name", "employee__first_name"],
                "unique_together": {("employee", "period", "motif")},
            },
        ),
        migrations.CreateModel(
            name="PayrollLineItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "base_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                ("is_fixed", models.BooleanField(default=False)),
                ("is_imported", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_line_items",
                        to="core.employee",
                    ),
                ),
                (
                    "motif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_items",
                        to="core.payrollmotif",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="core.payroll",
                    ),
                ),
                (
                    "payroll_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_items",
                        to="core.payrollelement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Line Item",
                "verbose_name_plural": "Payroll Line Items",
                "db_table": "rubriquepaie",
                "ordering": ["payroll", "payroll_element__label"],
                "unique_together": {("payroll", "payroll_element")},
            },
        ),
        migrations.CreateModel(
            name="WorkedDays",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("period", models.DateField()),
                (
                    "worked_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worked_days_records",
                        to="core.employee",
                    ),
                ),
                (
                    "motif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worked_days_records",
                        to="core.payrollmotif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worked Days",
                "verbose_name_plural": "Worked Days",
                "db_table": "njtsalarie",
                "ordering": ["-period", "employee__last_name", "employee__first_name"],
                "unique_together": {("employee", "motif", "period")},
            },
        ),
    ]
