# Generated by Django 5.2.5 on 2025-08-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_payroll_processing_models"),
    ]

    operations = [
        # First remove the current foreign key constraint
        migrations.AlterField(
            model_name='payroll',
            name='processed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='processed_payrolls',
                to='core.user'  # Reference our custom User model
            ),
        ),
    ]
