# Generated by Django 5.2.5 on 2025-08-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_fix_payroll_user_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentDeduction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("period", models.DateField(blank=True, null=True)),
                ("agreement_date", models.DateField()),
                (
                    "capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "installment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "current_installment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                (
                    "current_installment_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_settled", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_deductions",
                        to="core.employee",
                    ),
                ),
                (
                    "payroll_element",
                    models.ForeignKey(
                        db_column="rubrique",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_deductions",
                        to="core.payrollelement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Installment Deduction",
                "verbose_name_plural": "Installment Deductions",
                "db_table": "retenuesaecheances",
                "ordering": [
                    "agreement_date",
                    "employee__last_name",
                    "employee__first_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="InstallmentTranche",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("period", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("motif", models.IntegerField(blank=True, null=True)),
                ("sequence_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installment_deduction",
                    models.ForeignKey(
                        db_column="retenueAEcheances",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_tranches",
                        to="core.installmentdeduction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Installment Tranche",
                "verbose_name_plural": "Installment Tranches",
                "db_table": "tranchesretenuesaecheances",
                "ordering": ["installment_deduction", "period", "sequence_number"],
                "unique_together": {
                    ("installment_deduction", "period", "sequence_number")
                },
            },
        ),
    ]
