# Generated by Django 5.2.5 on 2025-08-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_deductions_benefits"),
    ]

    operations = [
        migrations.CreateModel(
            name="CNAMDeclaration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("declaration_period", models.DateField()),
                (
                    "employee_function_number",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("cnam_number", models.CharField(blank=True, max_length=50)),
                ("nni", models.CharField(blank=True, max_length=50)),
                ("employee_name", models.CharField(max_length=200)),
                ("entry_date", models.CharField(blank=True, max_length=20)),
                ("exit_date", models.CharField(blank=True, max_length=20)),
                (
                    "taxable_base_month1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "taxable_base_month2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "taxable_base_month3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "working_days_month1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "working_days_month2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "working_days_month3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("submission_reference", models.CharField(blank=True, max_length=50)),
                (
                    "total_taxable_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_working_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cnam_contribution_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cnam_contribution_employer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_cnam_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnam_declarations",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "listenominativecnam",
                "ordering": ["-declaration_period", "employee_name"],
                "unique_together": {("employee", "declaration_period")},
            },
        ),
        migrations.CreateModel(
            name="CNSSDeclaration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("declaration_period", models.DateField()),
                ("cnss_number", models.CharField(blank=True, max_length=50)),
                ("employee_name", models.CharField(max_length=200)),
                ("working_days_month1", models.CharField(blank=True, max_length=10)),
                ("working_days_month2", models.CharField(blank=True, max_length=10)),
                ("working_days_month3", models.CharField(blank=True, max_length=10)),
                (
                    "total_working_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "actual_remuneration",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "contribution_ceiling",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("hire_date", models.CharField(blank=True, max_length=20)),
                ("termination_date", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("submission_reference", models.CharField(blank=True, max_length=50)),
                (
                    "cnss_contribution_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cnss_contribution_employer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_cnss_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnss_declarations",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "listenominativecnss",
                "ordering": ["-declaration_period", "employee_name"],
                "unique_together": {("employee", "declaration_period")},
            },
        ),
    ]
