# Generated by Django 5.2.5 on 2025-08-14 16:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_compliance_reporting"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterPiece",
            fields=[
                (
                    "numero",
                    models.CharField(
                        help_text="Document number (sequence or timestamp based)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "libelle_service",
                    models.CharField(
                        default="Service Paie",
                        help_text="Service description",
                        max_length=200,
                    ),
                ),
                ("dateop", models.DateField(help_text="Operation date")),
                (
                    "rubrique",
                    models.CharField(
                        help_text="Motif name for this accounting period",
                        max_length=100,
                    ),
                ),
                (
                    "beneficiaire",
                    models.CharField(
                        default="-",
                        help_text="Beneficiary (legacy uses '-')",
                        max_length=200,
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total debit amount",
                        max_digits=15,
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total credit amount",
                        max_digits=15,
                    ),
                ),
                (
                    "initiateur",
                    models.CharField(
                        help_text="User who initiated the accounting piece",
                        max_length=100,
                    ),
                ),
                (
                    "init_hr",
                    models.DateTimeField(
                        help_text="Timestamp when piece was initiated"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATED", "Validated"),
                            ("EXPORTED", "Exported"),
                            ("INTEGRATED", "Integrated to external system"),
                        ],
                        default="DRAFT",
                        help_text="Integration status with external accounting systems",
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="Payroll period (YYYY-MM format)", max_length=20
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        help_text="Payroll motif for this piece", max_length=100
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference from external accounting system",
                        max_length=100,
                    ),
                ),
                (
                    "export_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when exported to external system",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        help_text="User who approved the piece",
                        max_length=100,
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of approval", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "masterpiece",
                "ordering": ["-dateop", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["period", "motif"], name="masterpiece_period_375e77_idx"
                    ),
                    models.Index(
                        fields=["dateop"], name="masterpiece_dateop_677101_idx"
                    ),
                    models.Index(
                        fields=["status"], name="masterpiece_status_e3742e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DetailPiece",
            fields=[
                (
                    "numligne",
                    models.BigAutoField(
                        help_text="Line number (auto-generated)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dateop", models.DateField(help_text="Operation date")),
                (
                    "journal",
                    models.CharField(
                        default="PAI",
                        help_text="Journal code (default: PAI for payroll)",
                        max_length=10,
                    ),
                ),
                ("compte", models.CharField(help_text="Account number", max_length=50)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Transaction description", max_length=300
                    ),
                ),
                (
                    "intitulet",
                    models.CharField(help_text="Account title/name", max_length=200),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, help_text="Transaction amount", max_digits=15
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")],
                        help_text="Transaction direction (D=Debit, C=Credit)",
                        max_length=1,
                    ),
                ),
                (
                    "cvmro_montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Mirror amount (same as montant)",
                        max_digits=15,
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="UM",
                        help_text="Currency code (default: UM)",
                        max_length=10,
                    ),
                ),
                (
                    "cours",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Exchange rate (default: 1.0000)",
                        max_digits=10,
                    ),
                ),
                (
                    "numero_cours",
                    models.IntegerField(
                        default=1, help_text="Exchange rate number (default: 1)"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("RUBRIQUE", "Payroll rubrique"),
                            ("BANK", "Bank transfer"),
                            ("CASH", "Cash payment"),
                            ("ENGAGEMENT", "Employee engagement"),
                            ("STATUTORY", "Statutory obligation"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of account posting",
                        max_length=20,
                    ),
                ),
                (
                    "chapitre",
                    models.CharField(
                        blank=True,
                        help_text="Chapter code for external systems",
                        max_length=50,
                    ),
                ),
                (
                    "exported",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this line was exported to external system",
                    ),
                ),
                (
                    "export_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference from external system export",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee reference for individual postings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_details",
                        to="core.employee",
                    ),
                ),
                (
                    "nupiece",
                    models.ForeignKey(
                        help_text="Reference to master piece",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailpieces",
                        to="core.masterpiece",
                    ),
                ),
            ],
            options={
                "db_table": "detailpiece",
                "ordering": ["numligne"],
                "indexes": [
                    models.Index(
                        fields=["nupiece", "compte"],
                        name="detailpiece_nupiece_6de34b_idx",
                    ),
                    models.Index(
                        fields=["dateop"], name="detailpiece_dateop_20f822_idx"
                    ),
                    models.Index(fields=["sens"], name="detailpiece_sens_a05226_idx"),
                    models.Index(
                        fields=["account_type"], name="detailpiece_account_e2bb78_idx"
                    ),
                    models.Index(
                        fields=["employee"], name="detailpiece_employe_a8709d_idx"
                    ),
                ],
            },
        ),
    ]
