package com.mccmr.ui;

import com.mccmr.entity.Paramgen;
import com.mccmr.entity.Semainetravail;
import com.mccmr.entity.Sysrubrique;
import com.mccmr.icon.GoogleMaterialDesignIcons;
import com.mccmr.icon.IconFontSwing;
import com.mccmr.util.GeneralLib;
import com.mccmr.util.ModelClass;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Objects;
import javax.imageio.ImageIO;
import javax.persistence.Query;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import org.hibernate.HibernateException;

public class parametres extends JInternalFrame {
   public menu menu;
   private JButton CancelActivateButton;
   private JButton activateButton;
   private JPanel activatePanel;
   private JButton btnExit;
   private JButton btnSave;
   private JCheckBox cAddCurrentSalInCumulCng;
   private JCheckBox cAncienneteAuto;
   private JCheckBox cAppIndCompensatrice;
   private JCheckBox cDIMBegin;
   private JCheckBox cDIMEnd;
   private JCheckBox cDIMwe;
   private JCheckBox cDeductionCNAMdeITS;
   private JCheckBox cDeductionCNSSdeITS;
   private JCheckBox cIndlogementAuto;
   private JCheckBox cJEUBegin;
   private JCheckBox cJEUEnd;
   private JCheckBox cJEUwe;
   private JCheckBox cLUNBegin;
   private JCheckBox cLUNEnd;
   private JCheckBox cLUNwe;
   private JCheckBox cMARBegin;
   private JCheckBox cMAREnd;
   private JCheckBox cMARwe;
   private JCheckBox cMERBegin;
   private JCheckBox cMEREnd;
   private JCheckBox cMERwe;
   private JCheckBox cMailSmtpTLSEnabled;
   private JCheckBox cPrimePanierAuto;
   private JCheckBox cRemboursementITS;
   private JCheckBox cRetEngOnConge;
   private JCheckBox cSAMBegin;
   private JCheckBox cSAMEnd;
   private JCheckBox cSAMwe;
   private JCheckBox cVENBegin;
   private JCheckBox cVENEnd;
   private JCheckBox cVENwe;
   private JButton jButton1;
   private JButton jButton2;
   private JLabel jLabel10;
   private JLabel jLabel11;
   private JLabel jLabel12;
   private JLabel jLabel13;
   private JLabel jLabel14;
   private JLabel jLabel15;
   private JLabel jLabel16;
   private JLabel jLabel17;
   private JLabel jLabel18;
   private JLabel jLabel19;
   private JLabel jLabel20;
   private JLabel jLabel21;
   private JLabel jLabel22;
   private JLabel jLabel23;
   private JLabel jLabel24;
   private JLabel jLabel25;
   private JLabel jLabel26;
   private JLabel jLabel27;
   private JLabel jLabel28;
   private JLabel jLabel29;
   private JLabel jLabel3;
   private JLabel jLabel30;
   private JLabel jLabel31;
   private JLabel jLabel34;
   private JLabel jLabel38;
   private JLabel jLabel39;
   private JLabel jLabel4;
   private JLabel jLabel40;
   private JLabel jLabel41;
   private JLabel jLabel42;
   private JLabel jLabel43;
   private JLabel jLabel44;
   private JLabel jLabel45;
   private JLabel jLabel46;
   private JLabel jLabel47;
   private JLabel jLabel48;
   private JLabel jLabel49;
   private JLabel jLabel5;
   private JLabel jLabel50;
   private JLabel jLabel51;
   private JLabel jLabel52;
   private JLabel jLabel53;
   private JLabel jLabel54;
   private JLabel jLabel55;
   private JLabel jLabel56;
   private JLabel jLabel57;
   private JLabel jLabel58;
   private JLabel jLabel59;
   private JLabel jLabel6;
   private JLabel jLabel60;
   private JLabel jLabel61;
   private JLabel jLabel62;
   private JLabel jLabel63;
   private JLabel jLabel64;
   private JLabel jLabel65;
   private JLabel jLabel66;
   private JLabel jLabel67;
   private JLabel jLabel68;
   private JLabel jLabel7;
   private JLabel jLabel8;
   private JLabel jLabel9;
   private JLabel jLabel97;
   private JPanel jPanel1;
   private JPanel jPanel10;
   private JPanel jPanel11;
   private JPanel jPanel2;
   private JPanel jPanel3;
   private JPanel jPanel4;
   private JPanel jPanel5;
   private JPanel jPanel6;
   private JPanel jPanel8;
   private JPanel jPanel9;
   private JScrollPane jScrollPane1;
   private JScrollPane jScrollPane2;
   private JScrollPane jScrollPane7;
   private JTabbedPane jTabbedPane1;
   private JLabel lLastUpdate;
   private JLabel lbClientName;
   private JLabel msgErrLabel;
   private JButton photoButton;
   private JProgressBar progressBar;
   private JTable sysRubriqueTable;
   private JFormattedTextField tAbattement;
   private JTextField tActiveCode;
   private JTextField tActiviteEntreprise;
   private JTextArea tAdresse;
   private JTextField tBP;
   private JTextField tBankVirement;
   private JTextField tCNAM;
   private JTextField tCNSS;
   private JTextField tCheminAtt2000;
   private JTextField tCpteVirement;
   private JDateChooser tDateCurentLicence;
   private JDateChooser tDateInitLicence;
   private JFormattedTextField tDelaiAlerteFinContrat;
   private JTextField tDevises;
   private JTextField tEmail;
   private JTextField tEmailTest;
   private JTextField tFax;
   private JTextField tITS;
   private JFormattedTextField tLicencePeriodicity;
   private JTextField tLogo;
   private JTextField tLogoDestFile;
   private JLabel tLogoImg;
   private JPasswordField tMailPassword;
   private JTextField tMailSmtpHost;
   private JTextField tMailSmtpPort;
   private JTextField tMailUser;
   private JComboBox tModeITS;
   private JFormattedTextField tNjtDefault;
   private JFormattedTextField tNoComptaCNAM;
   private JFormattedTextField tNoComptaChapitreCnam;
   private JFormattedTextField tNoComptaChapitreCnamPatCredit;
   private JFormattedTextField tNoComptaChapitreCnamPatDebit;
   private JFormattedTextField tNoComptaChapitreCnss;
   private JFormattedTextField tNoComptaChapitreCnssMedCredit;
   private JFormattedTextField tNoComptaChapitreCnssMedDebit;
   private JFormattedTextField tNoComptaChapitreCnssPatCredit;
   private JFormattedTextField tNoComptaChapitreCnssPatDebit;
   private JFormattedTextField tNoComptaChapitreIts;
   private JFormattedTextField tNoComptaChapitreNet;
   private JFormattedTextField tNoComptaChapitreRcnam;
   private JFormattedTextField tNoComptaChapitreRcnss;
   private JFormattedTextField tNoComptaChapitreRits;
   private JTextField tNoComptaCleCnam;
   private JTextField tNoComptaCleCnamPatCredit;
   private JTextField tNoComptaCleCnamPatDebit;
   private JTextField tNoComptaCleCnss;
   private JTextField tNoComptaCleCnssMedCredit;
   private JTextField tNoComptaCleCnssMedDebit;
   private JTextField tNoComptaCleCnssPatCredit;
   private JTextField tNoComptaCleCnssPatDebit;
   private JTextField tNoComptaCleIts;
   private JTextField tNoComptaCleNet;
   private JTextField tNoComptaCleRcnam;
   private JTextField tNoComptaCleRcnss;
   private JTextField tNoComptaCleRits;
   private JFormattedTextField tNoComptaCnamPatCredit;
   private JFormattedTextField tNoComptaCnamPatDebit;
   private JFormattedTextField tNoComptaCnss;
   private JFormattedTextField tNoComptaCnssMedCredit;
   private JFormattedTextField tNoComptaCnssMedDebit;
   private JFormattedTextField tNoComptaCnssPatCredit;
   private JFormattedTextField tNoComptaCnssPatDebit;
   private JFormattedTextField tNoComptaIts;
   private JFormattedTextField tNoComptaNet;
   private JFormattedTextField tNoComptaRCNAM;
   private JFormattedTextField tNoComptaRITS;
   private JFormattedTextField tNoComptaRcnss;
   private JDateChooser tPeriodeCloture;
   private JDateChooser tPeriodeCourante;
   private JFormattedTextField tPlafonIndNonImposable;
   private JTextField tQualiRespo;
   private JFormattedTextField tQuotaEcheanceRAE;
   private JTextField tRespoansable;
   private JFormattedTextField tSMIG;
   private JTextArea tSignataires;
   private JTextField tSiteweb;
   private JTextField tTelephone;
   private JTextField tnomEntreprise;
   private JTextField tvilleSiege;

   public parametres() {
      this.initComponents();
      this.initIcons();
   }

   private void initIcons() {
      this.btnExit.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.CLOSE, 27.0F, new Color(0, 0, 51), new Color(255, 255, 255)));
      this.btnSave.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.SAVE, 27.0F, new Color(0, 0, 51), new Color(255, 255, 255)));
   }

   public void refresh() {
      this.findByID();
      this.afficherSysRubrique();
      this.tActiveCode.setEnabled(this.menu.paramsGen.getLicenceKey() == null);
      this.activateButton.setEnabled(this.menu.paramsGen.getLicenceKey() == null);
      this.CancelActivateButton.setEnabled(this.menu.paramsGen.getLicenceKey() != null);
      Query q = this.menu.entityManager.createQuery("Select p from Paie p");
      this.tPeriodeCourante.setEnabled(q.getResultList().isEmpty());
   }

   private void findByID() {
      this.menu.viewMessage(this.msgErrLabel, "", false);
      Paramgen paramgen = this.menu.paramsGen;
      this.tDevises.setText(paramgen.getDevise());
      this.lLastUpdate.setText(paramgen.getDateMaj().toString());
      this.tAdresse.setText(paramgen.getAdresse());
      this.tActiviteEntreprise.setText(paramgen.getActiviteEntreprise());
      this.tBP.setText(paramgen.getBd());
      this.tCNAM.setText(paramgen.getNoCnam());
      this.tCNSS.setText(paramgen.getNoCnss());
      this.tDelaiAlerteFinContrat.setValue(paramgen.getDelaiAlerteFinContrat());
      this.tEmail.setText(paramgen.getEmail());
      this.tFax.setText(paramgen.getFax());
      this.tITS.setText(paramgen.getNoIts());
      this.tPeriodeCloture.setDate(paramgen.getPeriodeCloture());
      this.tPeriodeCourante.setDate(paramgen.getPeriodeCourante());
      this.tNjtDefault.setValue(paramgen.getNjtDefault());
      this.tNoComptaCNAM.setValue(paramgen.getNoComptaCnam());
      this.tNoComptaChapitreCnam.setValue(paramgen.getNoComptaChapitreCnam());
      this.tNoComptaCleCnam.setText(paramgen.getNoComptaCleCnam());
      this.tNoComptaCnamPatCredit.setValue(paramgen.getNoComptaCnamPatCredit());
      this.tNoComptaChapitreCnamPatCredit.setValue(paramgen.getNoComptaChapitreCnamPatCredit());
      this.tNoComptaCleCnamPatCredit.setText(paramgen.getNoComptaCleCnamPatCredit());
      this.tNoComptaCnamPatDebit.setValue(paramgen.getNoComptaCnamPatDebit());
      this.tNoComptaChapitreCnamPatDebit.setValue(paramgen.getNoComptaChapitreCnamPatDebit());
      this.tNoComptaCleCnamPatDebit.setText(paramgen.getNoComptaCleCnamPatDebit());
      this.tNoComptaCnss.setValue(paramgen.getNoComptaCnss());
      this.tNoComptaChapitreCnss.setValue(paramgen.getNoComptaChapitreCnss());
      this.tNoComptaCleCnss.setText(paramgen.getNoComptaCleCnss());
      this.tNoComptaCnssMedCredit.setValue(paramgen.getNoComptaCnssMedCredit());
      this.tNoComptaChapitreCnssMedCredit.setValue(paramgen.getNoComptaChapitreCnssMedCredit());
      this.tNoComptaCleCnssMedCredit.setText(paramgen.getNoComptaCleCnssMedCredit());
      this.tNoComptaCnssMedDebit.setValue(paramgen.getNoComptaCnssMedDebit());
      this.tNoComptaChapitreCnssMedDebit.setValue(paramgen.getNoComptaChapitreCnssMedDebit());
      this.tNoComptaCleCnssMedDebit.setText(paramgen.getNoComptaCleCnssMedDebit());
      this.tNoComptaCnssPatCredit.setValue(paramgen.getNoComptaCnssPatCredit());
      this.tNoComptaChapitreCnssPatCredit.setValue(paramgen.getNoComptaChapitreCnssPatCredit());
      this.tNoComptaCleCnssPatCredit.setText(paramgen.getNoComptaCleCnssPatCredit());
      this.tNoComptaCnssPatDebit.setValue(paramgen.getNoComptaCnssPatDebit());
      this.tNoComptaChapitreCnssPatDebit.setValue(paramgen.getNoComptaChapitreCnssPatDebit());
      this.tNoComptaCleCnssPatDebit.setText(paramgen.getNoComptaCleCnssPatDebit());
      this.tNoComptaIts.setValue(paramgen.getNoComptaIts());
      this.tNoComptaChapitreIts.setValue(paramgen.getNoComptaChapitreIts());
      this.tNoComptaCleIts.setText(paramgen.getNoComptaCleIts());
      this.tNoComptaNet.setValue(paramgen.getNoComptaNet());
      this.tNoComptaChapitreNet.setValue(paramgen.getNoComptaChapitreNet());
      this.tNoComptaCleNet.setText(paramgen.getNoComptaCleNet());
      this.tNoComptaRITS.setValue(paramgen.getNoComptaRits());
      this.tNoComptaChapitreRits.setValue(paramgen.getNoComptaChapitreRits());
      this.tNoComptaCleRits.setText(paramgen.getNoComptaCleRits());
      this.tNoComptaRcnss.setValue(paramgen.getNoComptaRcnss());
      this.tNoComptaChapitreRcnss.setValue(paramgen.getNoComptaChapitreRcnss());
      this.tNoComptaCleRcnss.setText(paramgen.getNoComptaCleRcnss());
      this.tNoComptaRCNAM.setValue(paramgen.getNoComptaRcnam());
      this.tNoComptaChapitreRcnam.setValue(paramgen.getNoComptaChapitreRcnam());
      this.tNoComptaCleRcnam.setText(paramgen.getNoComptaCleRcnam());
      this.tPlafonIndNonImposable.setValue(paramgen.getPlafonIndNonImposable());
      this.tQualiRespo.setText(paramgen.getQualiteResponsable());
      this.tRespoansable.setText(paramgen.getResponsableEntreprise());
      this.tSMIG.setValue(paramgen.getSmig());
      this.tSignataires.setText(paramgen.getSignataires());
      this.tSiteweb.setText(paramgen.getSiteweb());
      this.tTelephone.setText(paramgen.getTelephone());
      this.tActiviteEntreprise.setText(paramgen.getVilleSiege());
      this.tnomEntreprise.setText(paramgen.getNomEntreprise());
      this.tvilleSiege.setText(paramgen.getVilleSiege());
      this.cAncienneteAuto.setSelected(paramgen.isAncienneteAuto());
      this.cDeductionCNAMdeITS.setSelected(paramgen.isDeductionCnamdeIts());
      this.cDeductionCNSSdeITS.setSelected(paramgen.isDeductionCnssdeIts());
      this.cIndlogementAuto.setSelected(paramgen.isIndlogementAuto());
      this.cPrimePanierAuto.setSelected(paramgen.isPrimePanierAuto());
      this.cRemboursementITS.setSelected(paramgen.isRemboursementIts());
      this.tCheminAtt2000.setText(paramgen.getCheminatt2000());
      this.tBankVirement.setText(paramgen.getBankvirement());
      this.tCpteVirement.setText(paramgen.getComptevirement());
      this.tAbattement.setValue(paramgen.getAbatement());
      this.tQuotaEcheanceRAE.setValue(paramgen.getQuotaEcheanceRae());
      this.cRetEngOnConge.setSelected(paramgen.isRetEngOnConge());
      this.tMailSmtpHost.setText(paramgen.getMailSmtpHost());
      this.tMailUser.setText(paramgen.getMailUser());
      this.tMailPassword.setText(paramgen.getMailPassword());
      this.tMailSmtpPort.setText(paramgen.getMailSmtpPort());
      this.cMailSmtpTLSEnabled.setSelected(paramgen.isMailSmtpTLSEnabled());
      this.cAppIndCompensatrice.setSelected(paramgen.isAppIndCompensatrice());
      this.cAddCurrentSalInCumulCng.setSelected(paramgen.isAddCurrentSalInCumulCng());
      this.tModeITS.setSelectedItem(paramgen.getModeITS());
      this.tDateInitLicence.setDate(paramgen.getDateInitLicence());
      this.tDateCurentLicence.setDate(paramgen.getDateCurentLicence());
      this.tLicencePeriodicity.setText(paramgen.getLicencePeriodicity());
      if (paramgen.getLogo() != null && paramgen.getLogo().length > 0) {
         byte[] bAvatar = paramgen.getLogo();
         String fileName = "logo.png";
         File file = new File(fileName);
         file.deleteOnExit();

         try {
            FileOutputStream fos = new FileOutputStream(fileName);
            fos.write(bAvatar);
            fos.close();
            file = new File(fileName);
            BufferedImage img = ImageIO.read(file);
            ImageIcon icon = new ImageIcon(img);
            Image zoom = GeneralLib.scaleImage(icon.getImage(), 100, 100);
            Icon iconScaled = new ImageIcon(zoom);
            this.tLogoImg.setIcon(iconScaled);
            this.tLogoImg.revalidate();
            this.tLogoImg.repaint();
         } catch (Exception e) {
            e.printStackTrace();
         }
      }

      try {
         Query q = this.menu.entityManager.createQuery("Select p from Semainetravail p");
         q.setMaxResults(1000000);

         for(Object o : q.getResultList()) {
            Semainetravail rs = (Semainetravail)o;
            switch (rs.getJour()) {
               case "dimanche":
                  this.cDIMBegin.setSelected(rs.isDebut());
                  this.cDIMEnd.setSelected(rs.isFin());
                  this.cDIMwe.setSelected(rs.isWeekEnd());
               case "lundi":
                  this.cLUNBegin.setSelected(rs.isDebut());
                  this.cLUNEnd.setSelected(rs.isFin());
                  this.cLUNwe.setSelected(rs.isWeekEnd());
               case "mardi":
                  this.cMARBegin.setSelected(rs.isDebut());
                  this.cMAREnd.setSelected(rs.isFin());
                  this.cMARwe.setSelected(rs.isWeekEnd());
               case "merecredi":
                  this.cMERBegin.setSelected(rs.isDebut());
                  this.cMEREnd.setSelected(rs.isFin());
                  this.cMERwe.setSelected(rs.isWeekEnd());
               case "jeudi":
                  this.cJEUBegin.setSelected(rs.isDebut());
                  this.cJEUEnd.setSelected(rs.isFin());
                  this.cJEUwe.setSelected(rs.isWeekEnd());
               case "vendredi":
                  this.cVENBegin.setSelected(rs.isDebut());
                  this.cVENEnd.setSelected(rs.isFin());
                  this.cVENwe.setSelected(rs.isWeekEnd());
               case "samedi":
                  this.cSAMBegin.setSelected(rs.isDebut());
                  this.cSAMEnd.setSelected(rs.isFin());
                  this.cSAMwe.setSelected(rs.isWeekEnd());
            }
         }
      } catch (HibernateException he) {
         he.printStackTrace();
      }

   }

   private void afficherSysRubrique() {
      this.menu.mc.getClass();
      JTable var10000 = this.sysRubriqueTable;
      ModelClass var10003 = this.menu.mc;
      Objects.requireNonNull(var10003);
      var10000.setModel(new ModelClass.tmSysRubrique(var10003));
      this.sysRubriqueTable.setGridColor(new Color(0, 102, 153));
      this.sysRubriqueTable.setSelectionBackground(new Color(0, 102, 153));
      this.sysRubriqueTable.setShowGrid(false);

      try {
         Query q = this.menu.entityManager.createQuery("Select p from Sysrubrique p order by p.idSys");
         q.setMaxResults(1000000);

         for(Object o : q.getResultList()) {
            ((ModelClass.tmSysRubrique)this.sysRubriqueTable.getModel()).addRow((Sysrubrique)o);
         }

         this.sysRubriqueTable.getColumnModel().getColumn(1).setPreferredWidth(400);
      } catch (HibernateException he) {
         he.printStackTrace();
      }

   }

   private void initComponents() {
      this.jPanel1 = new JPanel();
      this.jLabel7 = new JLabel();
      this.btnExit = new JButton();
      this.jTabbedPane1 = new JTabbedPane();
      this.jPanel2 = new JPanel();
      this.jLabel3 = new JLabel();
      this.tnomEntreprise = new JTextField();
      this.jLabel4 = new JLabel();
      this.tActiviteEntreprise = new JTextField();
      this.jLabel5 = new JLabel();
      this.tTelephone = new JTextField();
      this.tFax = new JTextField();
      this.jLabel6 = new JLabel();
      this.jLabel8 = new JLabel();
      this.jScrollPane1 = new JScrollPane();
      this.tAdresse = new JTextArea();
      this.jLabel9 = new JLabel();
      this.tBP = new JTextField();
      this.jLabel10 = new JLabel();
      this.tSiteweb = new JTextField();
      this.jLabel11 = new JLabel();
      this.tEmail = new JTextField();
      this.jLabel12 = new JLabel();
      this.tCNSS = new JTextField();
      this.tCNAM = new JTextField();
      this.jLabel13 = new JLabel();
      this.tITS = new JTextField();
      this.jLabel14 = new JLabel();
      this.jLabel28 = new JLabel();
      this.tvilleSiege = new JTextField();
      this.jLabel17 = new JLabel();
      this.tCheminAtt2000 = new JTextField();
      this.tLogo = new JTextField();
      this.photoButton = new JButton();
      this.jLabel19 = new JLabel();
      this.tLogoImg = new JLabel();
      this.tLogoDestFile = new JTextField();
      this.jLabel20 = new JLabel();
      this.tBankVirement = new JTextField();
      this.jLabel48 = new JLabel();
      this.tCpteVirement = new JTextField();
      this.jPanel3 = new JPanel();
      this.cPrimePanierAuto = new JCheckBox();
      this.cRemboursementITS = new JCheckBox();
      this.cAncienneteAuto = new JCheckBox();
      this.jLabel21 = new JLabel();
      this.jLabel27 = new JLabel();
      this.cIndlogementAuto = new JCheckBox();
      this.cDeductionCNSSdeITS = new JCheckBox();
      this.cDeductionCNAMdeITS = new JCheckBox();
      this.jLabel30 = new JLabel();
      this.jLabel31 = new JLabel();
      this.tPlafonIndNonImposable = new JFormattedTextField();
      this.tNjtDefault = new JFormattedTextField();
      this.tDelaiAlerteFinContrat = new JFormattedTextField();
      this.tSMIG = new JFormattedTextField();
      this.jLabel47 = new JLabel();
      this.tModeITS = new JComboBox();
      this.jLabel40 = new JLabel();
      this.jLabel97 = new JLabel();
      this.tPeriodeCloture = new JDateChooser();
      this.tAbattement = new JFormattedTextField();
      this.jLabel52 = new JLabel();
      this.tQuotaEcheanceRAE = new JFormattedTextField();
      this.jLabel53 = new JLabel();
      this.cRetEngOnConge = new JCheckBox();
      this.tDevises = new JTextField();
      this.jLabel54 = new JLabel();
      this.jLabel55 = new JLabel();
      this.jLabel56 = new JLabel();
      this.tMailSmtpHost = new JTextField();
      this.tMailUser = new JTextField();
      this.jButton1 = new JButton();
      this.jLabel57 = new JLabel();
      this.tEmailTest = new JTextField();
      this.tMailSmtpPort = new JTextField();
      this.jLabel58 = new JLabel();
      this.cMailSmtpTLSEnabled = new JCheckBox();
      this.tMailPassword = new JPasswordField();
      this.jButton2 = new JButton();
      this.cAppIndCompensatrice = new JCheckBox();
      this.cAddCurrentSalInCumulCng = new JCheckBox();
      this.jLabel68 = new JLabel();
      this.tPeriodeCourante = new JDateChooser();
      this.jPanel5 = new JPanel();
      this.jLabel22 = new JLabel();
      this.jLabel23 = new JLabel();
      this.jLabel24 = new JLabel();
      this.jLabel25 = new JLabel();
      this.jLabel26 = new JLabel();
      this.tNoComptaIts = new JFormattedTextField();
      this.tNoComptaCnss = new JFormattedTextField();
      this.tNoComptaCNAM = new JFormattedTextField();
      this.tNoComptaRITS = new JFormattedTextField();
      this.tNoComptaNet = new JFormattedTextField();
      this.tNoComptaRcnss = new JFormattedTextField();
      this.jLabel50 = new JLabel();
      this.tNoComptaRCNAM = new JFormattedTextField();
      this.jLabel51 = new JLabel();
      this.jLabel59 = new JLabel();
      this.tNoComptaCnssMedCredit = new JFormattedTextField();
      this.jLabel60 = new JLabel();
      this.tNoComptaCnssMedDebit = new JFormattedTextField();
      this.jLabel61 = new JLabel();
      this.jLabel62 = new JLabel();
      this.tNoComptaCnssPatCredit = new JFormattedTextField();
      this.tNoComptaCnssPatDebit = new JFormattedTextField();
      this.tNoComptaCnamPatCredit = new JFormattedTextField();
      this.jLabel63 = new JLabel();
      this.tNoComptaCnamPatDebit = new JFormattedTextField();
      this.jLabel64 = new JLabel();
      this.tNoComptaChapitreIts = new JFormattedTextField();
      this.tNoComptaChapitreCnss = new JFormattedTextField();
      this.tNoComptaChapitreCnssMedCredit = new JFormattedTextField();
      this.tNoComptaChapitreCnssMedDebit = new JFormattedTextField();
      this.tNoComptaChapitreCnssPatCredit = new JFormattedTextField();
      this.tNoComptaChapitreCnssPatDebit = new JFormattedTextField();
      this.tNoComptaChapitreCnam = new JFormattedTextField();
      this.tNoComptaChapitreCnamPatCredit = new JFormattedTextField();
      this.tNoComptaChapitreCnamPatDebit = new JFormattedTextField();
      this.tNoComptaChapitreNet = new JFormattedTextField();
      this.tNoComptaChapitreRits = new JFormattedTextField();
      this.tNoComptaChapitreRcnss = new JFormattedTextField();
      this.tNoComptaChapitreRcnam = new JFormattedTextField();
      this.jLabel65 = new JLabel();
      this.jLabel66 = new JLabel();
      this.jLabel67 = new JLabel();
      this.tNoComptaCleNet = new JTextField();
      this.tNoComptaCleIts = new JTextField();
      this.tNoComptaCleCnss = new JTextField();
      this.tNoComptaCleCnssMedCredit = new JTextField();
      this.tNoComptaCleCnssMedDebit = new JTextField();
      this.tNoComptaCleCnssPatCredit = new JTextField();
      this.tNoComptaCleCnssPatDebit = new JTextField();
      this.tNoComptaCleCnam = new JTextField();
      this.tNoComptaCleCnamPatCredit = new JTextField();
      this.tNoComptaCleCnamPatDebit = new JTextField();
      this.tNoComptaCleRits = new JTextField();
      this.tNoComptaCleRcnss = new JTextField();
      this.tNoComptaCleRcnam = new JTextField();
      this.jPanel4 = new JPanel();
      this.jPanel8 = new JPanel();
      this.jLabel16 = new JLabel();
      this.jLabel29 = new JLabel();
      this.jLabel34 = new JLabel();
      this.jLabel38 = new JLabel();
      this.jLabel41 = new JLabel();
      this.jLabel42 = new JLabel();
      this.jLabel43 = new JLabel();
      this.jLabel44 = new JLabel();
      this.jLabel45 = new JLabel();
      this.jLabel46 = new JLabel();
      this.cDIMBegin = new JCheckBox();
      this.cDIMEnd = new JCheckBox();
      this.cDIMwe = new JCheckBox();
      this.cLUNBegin = new JCheckBox();
      this.cLUNEnd = new JCheckBox();
      this.cLUNwe = new JCheckBox();
      this.cMARBegin = new JCheckBox();
      this.cMAREnd = new JCheckBox();
      this.cMARwe = new JCheckBox();
      this.cMERBegin = new JCheckBox();
      this.cMEREnd = new JCheckBox();
      this.cMERwe = new JCheckBox();
      this.cJEUBegin = new JCheckBox();
      this.cJEUEnd = new JCheckBox();
      this.cJEUwe = new JCheckBox();
      this.cVENBegin = new JCheckBox();
      this.cVENEnd = new JCheckBox();
      this.cVENwe = new JCheckBox();
      this.cSAMBegin = new JCheckBox();
      this.cSAMEnd = new JCheckBox();
      this.cSAMwe = new JCheckBox();
      this.jPanel6 = new JPanel();
      this.jLabel39 = new JLabel();
      this.jScrollPane2 = new JScrollPane();
      this.tSignataires = new JTextArea();
      this.jLabel15 = new JLabel();
      this.jLabel18 = new JLabel();
      this.tQualiRespo = new JTextField();
      this.tRespoansable = new JTextField();
      this.jPanel9 = new JPanel();
      this.jScrollPane7 = new JScrollPane();
      this.sysRubriqueTable = new JTable();
      this.jPanel10 = new JPanel();
      this.activatePanel = new JPanel();
      this.tActiveCode = new JTextField();
      this.jLabel49 = new JLabel();
      this.lbClientName = new JLabel();
      this.activateButton = new JButton();
      this.CancelActivateButton = new JButton();
      this.tDateInitLicence = new JDateChooser();
      this.tLicencePeriodicity = new JFormattedTextField();
      this.tDateCurentLicence = new JDateChooser();
      this.jPanel11 = new JPanel();
      this.msgErrLabel = new JLabel();
      this.lLastUpdate = new JLabel();
      this.btnSave = new JButton();
      this.progressBar = new JProgressBar();
      this.jPanel1.setBackground(new Color(255, 255, 255));
      this.jPanel1.setForeground(new Color(0, 102, 153));
      this.jLabel7.setFont(new Font("Segoe UI Light", 0, 24));
      this.jLabel7.setForeground(new Color(0, 102, 153));
      this.jLabel7.setText("Param\u00e8tres");
      this.jLabel7.setToolTipText("");
      this.btnExit.setContentAreaFilled(false);
      this.btnExit.setCursor(new Cursor(0));
      this.btnExit.setOpaque(true);
      this.btnExit.addActionListener(new 1(this));
      GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
      this.jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(this.jLabel7, -2, 497, -2).addPreferredGap(ComponentPlacement.RELATED, -1, 32767).addComponent(this.btnExit, -2, 39, -2).addContainerGap()));
      jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addComponent(this.btnExit, -1, -1, 32767).addComponent(this.jLabel7, -1, -1, 32767));
      this.jTabbedPane1.setFont(new Font("Tahoma", 1, 11));
      this.jLabel3.setFont(new Font("Tahoma", 1, 11));
      this.jLabel3.setText("Nom entreprise");
      this.tnomEntreprise.setEditable(false);
      this.jLabel4.setFont(new Font("Tahoma", 1, 11));
      this.jLabel4.setText("Activit\u00e9");
      this.jLabel5.setFont(new Font("Tahoma", 1, 11));
      this.jLabel5.setText("T\u00e9l\u00e9phone");
      this.jLabel6.setFont(new Font("Tahoma", 1, 11));
      this.jLabel6.setText("Fax");
      this.jLabel8.setFont(new Font("Tahoma", 1, 11));
      this.jLabel8.setText("Adresse");
      this.tAdresse.setColumns(20);
      this.tAdresse.setFont(new Font("Tahoma", 0, 11));
      this.tAdresse.setRows(5);
      this.jScrollPane1.setViewportView(this.tAdresse);
      this.jLabel9.setFont(new Font("Tahoma", 1, 11));
      this.jLabel9.setText("BP");
      this.jLabel10.setFont(new Font("Tahoma", 1, 11));
      this.jLabel10.setText("Siteweb");
      this.jLabel11.setFont(new Font("Tahoma", 1, 11));
      this.jLabel11.setText("E-mail");
      this.jLabel12.setFont(new Font("Tahoma", 1, 11));
      this.jLabel12.setText("N\u00b0 CNSS");
      this.jLabel13.setFont(new Font("Tahoma", 1, 11));
      this.jLabel13.setHorizontalAlignment(4);
      this.jLabel13.setText("N\u00b0 CNAM");
      this.jLabel14.setFont(new Font("Tahoma", 1, 11));
      this.jLabel14.setHorizontalAlignment(4);
      this.jLabel14.setText("NIF");
      this.jLabel28.setFont(new Font("Tahoma", 1, 11));
      this.jLabel28.setText("Ville si\u00e8ge");
      this.jLabel17.setFont(new Font("Tahoma", 1, 11));
      this.jLabel17.setText("Chemin ATT2000");
      this.tLogo.setEditable(false);
      this.tLogo.setFont(new Font("Tahoma", 0, 9));
      this.tLogo.setHorizontalAlignment(0);
      this.photoButton.setFont(new Font("Tahoma", 1, 11));
      this.photoButton.setText("Parcourir...");
      this.photoButton.setCursor(new Cursor(0));
      this.photoButton.addActionListener(new 2(this));
      this.jLabel19.setFont(new Font("Tahoma", 1, 11));
      this.jLabel19.setText("Logo entreprise");
      this.tLogoImg.setBackground(new Color(255, 255, 255));
      this.tLogoImg.setHorizontalAlignment(0);
      this.tLogoImg.setBorder(BorderFactory.createEtchedBorder());
      this.tLogoImg.setOpaque(true);
      this.tLogoDestFile.setEditable(false);
      this.tLogoDestFile.setFont(new Font("Tahoma", 0, 8));
      this.tLogoDestFile.setHorizontalAlignment(0);
      this.jLabel20.setFont(new Font("Tahoma", 1, 11));
      this.jLabel20.setText("Banque virement");
      this.jLabel48.setFont(new Font("Tahoma", 1, 11));
      this.jLabel48.setText("N\u00b0 Cpte virement");
      GroupLayout jPanel2Layout = new GroupLayout(this.jPanel2);
      this.jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.jLabel5, -1, -1, 32767).addComponent(this.jLabel11, -1, -1, 32767).addComponent(this.jLabel4, -1, -1, 32767).addComponent(this.jLabel3, -1, 125, 32767)).addComponent(this.jLabel10, -2, 56, -2).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.jLabel28, -1, -1, 32767).addComponent(this.jLabel8, Alignment.TRAILING, -1, -1, 32767))).addPreferredGap(ComponentPlacement.UNRELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addComponent(this.tSiteweb, -2, 314, -2).addGroup(Alignment.TRAILING, jPanel2Layout.createParallelGroup(Alignment.LEADING).addComponent(this.tEmail, -2, 314, -2).addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false).addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup().addComponent(this.tTelephone, -2, 217, -2).addGap(18, 18, 18).addComponent(this.jLabel6, -2, 39, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tFax)).addComponent(this.tActiviteEntreprise, Alignment.LEADING, -2, 489, -2)).addComponent(this.tnomEntreprise, -2, 314, -2)).addComponent(this.tvilleSiege, -2, 209, -2).addGroup(jPanel2Layout.createSequentialGroup().addGap(1, 1, 1).addComponent(this.jScrollPane1, -2, 332, -2).addGap(51, 51, 51).addComponent(this.jLabel9).addGap(10, 10, 10).addComponent(this.tBP, -2, 83, -2))).addPreferredGap(ComponentPlacement.RELATED, 224, 32767).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.tLogoImg, -1, 221, 32767).addComponent(this.jLabel19, -1, -1, 32767))).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false).addComponent(this.jLabel48, -1, -1, 32767).addComponent(this.jLabel20, -1, -1, 32767).addComponent(this.jLabel17, Alignment.LEADING, -1, 125, 32767).addComponent(this.jLabel12, -1, -1, 32767)).addPreferredGap(ComponentPlacement.UNRELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addComponent(this.tCheminAtt2000, -2, 314, -2).addComponent(this.tBankVirement, -2, 431, -2).addComponent(this.tCpteVirement, -2, 253, -2)).addGap(0, 0, 32767)).addGroup(jPanel2Layout.createSequentialGroup().addComponent(this.tCNSS, -2, 94, -2).addPreferredGap(ComponentPlacement.UNRELATED).addComponent(this.jLabel13, -2, 62, -2).addPreferredGap(ComponentPlacement.UNRELATED).addComponent(this.tCNAM, -2, 103, -2).addGap(20, 20, 20).addComponent(this.jLabel14, -2, 44, -2).addPreferredGap(ComponentPlacement.UNRELATED).addComponent(this.tITS, -2, 103, -2).addPreferredGap(ComponentPlacement.RELATED, -1, 32767).addComponent(this.photoButton)).addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addGap(0, 0, 32767).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false).addGroup(jPanel2Layout.createSequentialGroup().addGap(6, 6, 6).addComponent(this.tLogoDestFile)).addComponent(this.tLogo, -2, 53, -2)).addGap(24, 24, 24))))).addGap(71, 71, 71)));
      jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tnomEntreprise, -2, -1, -2).addComponent(this.jLabel3)).addGap(6, 6, 6)).addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addComponent(this.jLabel19).addPreferredGap(ComponentPlacement.RELATED))).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tActiviteEntreprise, -2, -1, -2).addComponent(this.jLabel4)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tTelephone, -2, -1, -2).addComponent(this.jLabel5).addComponent(this.jLabel6).addComponent(this.tFax, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel11).addComponent(this.tEmail, -2, -1, -2)).addGap(11, 11, 11).addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tSiteweb, -2, -1, -2).addComponent(this.jLabel10)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(this.jLabel8).addGap(37, 37, 37).addComponent(this.jLabel28, -2, 14, -2)).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addComponent(this.jScrollPane1, -2, 40, -2).addGroup(jPanel2Layout.createSequentialGroup().addGap(3, 3, 3).addComponent(this.jLabel9)).addComponent(this.tBP, -2, -1, -2)).addGap(6, 6, 6).addComponent(this.tvilleSiege, -2, -1, -2)))).addComponent(this.tLogoImg, -2, 205, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel12).addComponent(this.tCNSS, -2, -1, -2).addComponent(this.jLabel13).addComponent(this.tCNAM, -2, -1, -2).addComponent(this.jLabel14).addComponent(this.tITS, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addComponent(this.jLabel17).addComponent(this.tCheminAtt2000, -2, 20, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel20).addComponent(this.tBankVirement, -2, 20, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel48).addComponent(this.tCpteVirement, -2, 20, -2)).addGap(140, 140, 140)).addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addComponent(this.photoButton).addPreferredGap(ComponentPlacement.RELATED, -1, 32767).addComponent(this.tLogo, -2, 21, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tLogoDestFile, -2, -1, -2).addGap(36, 36, 36)))));
      this.jTabbedPane1.addTab("Infos Entreprise", this.jPanel2);
      this.cPrimePanierAuto.setText("Prime de panier auto");
      this.cRemboursementITS.setText("Rembourssement d'ITS");
      this.cAncienneteAuto.setText("Prime anciennet\u00e9 auto");
      this.jLabel21.setHorizontalAlignment(4);
      this.jLabel21.setText("Plafond RNI");
      this.jLabel27.setHorizontalAlignment(4);
      this.jLabel27.setText("SMIG");
      this.cIndlogementAuto.setText("Indemnit\u00e9 de logement auto");
      this.cDeductionCNSSdeITS.setText("Deduction CNSS / ITS");
      this.cDeductionCNAMdeITS.setText("Deduction CNAM / ITS");
      this.jLabel30.setHorizontalAlignment(4);
      this.jLabel30.setText("NJT par d\u00e9faut");
      this.jLabel31.setHorizontalAlignment(4);
      this.jLabel31.setText("D\u00e9lais alerte fin de contrat");
      this.tPlafonIndNonImposable.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));
      this.tPlafonIndNonImposable.setHorizontalAlignment(4);
      this.tNjtDefault.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNjtDefault.setHorizontalAlignment(4);
      this.tDelaiAlerteFinContrat.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tDelaiAlerteFinContrat.setHorizontalAlignment(4);
      this.tSMIG.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));
      this.tSMIG.setHorizontalAlignment(4);
      this.jLabel47.setHorizontalAlignment(4);
      this.jLabel47.setText("Mode ITS");
      this.tModeITS.setModel(new DefaultComboBoxModel(new String[]{"G", "T"}));
      this.jLabel40.setHorizontalAlignment(4);
      this.jLabel40.setText("P\u00e9riode de cl\u00f4ture");
      this.jLabel97.setHorizontalAlignment(4);
      this.jLabel97.setText("Devise");
      this.tPeriodeCloture.setDateFormatString("dd/MM/yyyy");
      this.tAbattement.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));
      this.tAbattement.setHorizontalAlignment(4);
      this.jLabel52.setHorizontalAlignment(4);
      this.jLabel52.setText("Abattement");
      this.tQuotaEcheanceRAE.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));
      this.tQuotaEcheanceRAE.setHorizontalAlignment(4);
      this.jLabel53.setHorizontalAlignment(4);
      this.jLabel53.setText("Quotite cessible engagement en % du salaire net");
      this.cRetEngOnConge.setText("Deduire les engagements sur cong\u00e9s");
      this.cRetEngOnConge.addActionListener(new 3(this));
      this.tDevises.setText("MRU");
      this.tDevises.setToolTipText("");
      this.jLabel54.setHorizontalAlignment(4);
      this.jLabel54.setText("SMTP Host");
      this.jLabel55.setHorizontalAlignment(4);
      this.jLabel55.setText("E-mail emeteur");
      this.jLabel56.setHorizontalAlignment(4);
      this.jLabel56.setText("Pwd e-mail");
      this.tMailSmtpHost.setToolTipText("");
      this.tMailUser.setToolTipText("");
      this.jButton1.setFont(new Font("Segoe UI Light", 1, 10));
      this.jButton1.setText("Tester");
      this.jButton1.addActionListener(new 4(this));
      this.jLabel57.setHorizontalAlignment(4);
      this.jLabel57.setText("Envoyer un e-mail de test \u00e0");
      this.tEmailTest.setToolTipText("");
      this.tMailSmtpPort.setToolTipText("");
      this.jLabel58.setHorizontalAlignment(4);
      this.jLabel58.setText("SMTP Port");
      this.cMailSmtpTLSEnabled.setText("App. SSL/TLS");
      this.cMailSmtpTLSEnabled.setToolTipText("Application de la securit\u00e9 SSL/TLS");
      this.jButton2.setFont(new Font("Segoe UI Light", 1, 12));
      this.jButton2.setText("Appliquer les valeurs par d\u00e9faut");
      this.jButton2.addActionListener(new 5(this));
      this.cAppIndCompensatrice.setText("Appliquer le traitement de l'indemnite compensatrice");
      this.cAddCurrentSalInCumulCng.setText("Inclure le salaire du mois courant dans le cumul de cong\u00e9s");
      this.jLabel68.setHorizontalAlignment(4);
      this.jLabel68.setText("P\u00e9riode courante initiale");
      this.tPeriodeCourante.setDateFormatString("dd/MM/yyyy");
      GroupLayout jPanel3Layout = new GroupLayout(this.jPanel3);
      this.jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.cIndlogementAuto, -1, 310, 32767).addComponent(this.cDeductionCNAMdeITS, -1, -1, 32767).addComponent(this.cDeductionCNSSdeITS, -1, -1, 32767).addComponent(this.cRemboursementITS, -1, -1, 32767).addComponent(this.cAncienneteAuto, -1, -1, 32767).addComponent(this.cPrimePanierAuto, -1, -1, 32767)).addComponent(this.cRetEngOnConge, -1, -1, 32767).addComponent(this.cAppIndCompensatrice, -1, -1, 32767).addComponent(this.cAddCurrentSalInCumulCng, -2, 0, 32767)).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addPreferredGap(ComponentPlacement.RELATED, -1, 32767).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false).addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING).addComponent(this.jLabel53, -2, 294, -2).addComponent(this.jLabel52, -2, 197, -2).addComponent(this.jLabel21, -2, 197, -2)).addComponent(this.jLabel27, -1, 300, 32767)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addGap(0, 0, 32767).addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING, false).addComponent(this.jLabel31, Alignment.LEADING, -1, 197, 32767).addComponent(this.jLabel30, Alignment.LEADING, -1, -1, 32767)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.tNjtDefault, -1, 186, 32767).addComponent(this.tDelaiAlerteFinContrat)).addGap(115, 115, 115)).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.tSMIG, -2, 92, -2).addGap(10, 10, 10).addComponent(this.jLabel47, -2, 122, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tModeITS, -2, 168, -2)).addComponent(this.tPlafonIndNonImposable, -2, 389, -2).addComponent(this.tAbattement, -2, 389, -2).addComponent(this.tQuotaEcheanceRAE, -2, 389, -2)).addGap(0, 0, 32767)))).addGroup(jPanel3Layout.createSequentialGroup().addGap(7, 7, 7).addComponent(this.jLabel97, -2, 68, -2).addGap(18, 18, 18).addComponent(this.tDevises, -2, 94, -2).addGap(0, 0, 32767)).addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addPreferredGap(ComponentPlacement.RELATED, -1, 32767).addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.jLabel68, -2, 185, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tPeriodeCourante, -2, 152, -2)).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addComponent(this.jLabel55, -2, 212, -2).addGroup(jPanel3Layout.createSequentialGroup().addGap(23, 23, 23).addComponent(this.jLabel54, -2, 198, -2))).addGap(25, 25, 25).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.tMailSmtpHost, -2, 173, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.jLabel58, -2, 87, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tMailSmtpPort, -2, 63, -2).addGap(18, 18, 18).addComponent(this.cMailSmtpTLSEnabled, -2, 126, -2)).addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING).addComponent(this.jButton1).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.tMailUser, -2, 231, -2).addGap(38, 38, 38).addComponent(this.jLabel56).addGap(7, 7, 7).addComponent(this.tMailPassword, -2, 102, -2))))).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addComponent(this.jButton2, -2, 256, -2).addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addComponent(this.jLabel40, -2, 125, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tPeriodeCloture, -2, 152, -2)))).addGap(85, 85, 85)))).addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.jLabel57, -2, 192, -2).addGap(7, 7, 7).addComponent(this.tEmailTest, -2, 248, -2).addGap(286, 286, 286)));
      jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGap(35, 35, 35).addComponent(this.cPrimePanierAuto).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cAncienneteAuto).addGap(4, 4, 4).addComponent(this.cAppIndCompensatrice).addGap(18, 18, 18).addComponent(this.cIndlogementAuto).addGap(18, 18, 18).addComponent(this.cRetEngOnConge)).addGroup(jPanel3Layout.createSequentialGroup().addGap(10, 10, 10).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tSMIG, -2, -1, -2).addComponent(this.jLabel27).addComponent(this.jLabel47).addComponent(this.tModeITS, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tPlafonIndNonImposable, -2, -1, -2).addComponent(this.jLabel21)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tAbattement, -2, -1, -2).addComponent(this.jLabel52)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tQuotaEcheanceRAE, -2, -1, -2).addComponent(this.jLabel53)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tNjtDefault, -2, -1, -2).addComponent(this.jLabel30, -2, 12, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tDelaiAlerteFinContrat, -2, -1, -2).addComponent(this.jLabel31))).addGroup(jPanel3Layout.createSequentialGroup().addGap(36, 36, 36).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel97).addComponent(this.tDevises, -2, -1, -2)))).addGap(18, 18, 18).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addComponent(this.tPeriodeCourante, -2, 25, -2).addComponent(this.jLabel68)).addPreferredGap(ComponentPlacement.RELATED)).addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addComponent(this.cAddCurrentSalInCumulCng).addGap(16, 16, 16))).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.cRemboursementITS).addComponent(this.jLabel40)).addPreferredGap(ComponentPlacement.UNRELATED).addComponent(this.cDeductionCNSSdeITS).addGap(14, 14, 14).addComponent(this.cDeductionCNAMdeITS)).addGroup(jPanel3Layout.createSequentialGroup().addComponent(this.tPeriodeCloture, -2, 25, -2).addGap(21, 21, 21).addComponent(this.jButton2, -2, 31, -2).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel54).addComponent(this.tMailSmtpHost, -2, -1, -2).addComponent(this.jLabel58).addComponent(this.tMailSmtpPort, -2, -1, -2).addComponent(this.cMailSmtpTLSEnabled)).addGap(2, 2, 2).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel55).addComponent(this.tMailUser, -2, -1, -2).addComponent(this.jLabel56).addComponent(this.tMailPassword, -2, -1, -2)))).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel57).addComponent(this.tEmailTest, -2, -1, -2)).addComponent(this.jButton1)).addGap(28, 28, 28)));
      this.jTabbedPane1.addTab("Options", this.jPanel3);
      this.jLabel22.setText("N\u00b0 Compte ITS");
      this.jLabel23.setText("N\u00b0 Compte CNSS Employ\u00e9");
      this.jLabel24.setText("N\u00b0 Compte RITS");
      this.jLabel25.setText("N\u00b0 Compte CNAM Employ\u00e9");
      this.jLabel26.setText("N\u00b0 Compte Net cash");
      this.tNoComptaIts.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaIts.setHorizontalAlignment(4);
      this.tNoComptaCnss.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaCnss.setHorizontalAlignment(4);
      this.tNoComptaCNAM.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaCNAM.setHorizontalAlignment(4);
      this.tNoComptaRITS.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaRITS.setHorizontalAlignment(4);
      this.tNoComptaNet.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaNet.setHorizontalAlignment(4);
      this.tNoComptaRcnss.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaRcnss.setHorizontalAlignment(4);
      this.jLabel50.setText("N\u00b0 Compte RCNSS");
      this.tNoComptaRCNAM.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaRCNAM.setHorizontalAlignment(4);
      this.jLabel51.setText("N\u00b0 Compte RCNAM");
      this.jLabel59.setText("N\u00b0 Compte CNSS M\u00e9decine (C)");
      this.tNoComptaCnssMedCredit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaCnssMedCredit.setHorizontalAlignment(4);
      this.jLabel60.setText("N\u00b0 Compte CNSS M\u00e9decine (D)");
      this.tNoComptaCnssMedDebit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaCnssMedDebit.setHorizontalAlignment(4);
      this.jLabel61.setText("N\u00b0 Compte CNSS Patronal (D)");
      this.jLabel62.setText("N\u00b0 Compte CNSS Patronal (C)");
      this.tNoComptaCnssPatCredit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaCnssPatCredit.setHorizontalAlignment(4);
      this.tNoComptaCnssPatDebit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaCnssPatDebit.setHorizontalAlignment(4);
      this.tNoComptaCnamPatCredit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaCnamPatCredit.setHorizontalAlignment(4);
      this.jLabel63.setText("N\u00b0 Compte CNAM Patronal (D)");
      this.tNoComptaCnamPatDebit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaCnamPatDebit.setHorizontalAlignment(4);
      this.jLabel64.setText("N\u00b0 Compte CNAM Patronal (C)");
      this.tNoComptaChapitreIts.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreIts.setHorizontalAlignment(4);
      this.tNoComptaChapitreCnss.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreCnss.setHorizontalAlignment(4);
      this.tNoComptaChapitreCnssMedCredit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreCnssMedCredit.setHorizontalAlignment(4);
      this.tNoComptaChapitreCnssMedDebit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreCnssMedDebit.setHorizontalAlignment(4);
      this.tNoComptaChapitreCnssPatCredit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreCnssPatCredit.setHorizontalAlignment(4);
      this.tNoComptaChapitreCnssPatDebit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreCnssPatDebit.setHorizontalAlignment(4);
      this.tNoComptaChapitreCnam.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreCnam.setHorizontalAlignment(4);
      this.tNoComptaChapitreCnamPatCredit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreCnamPatCredit.setHorizontalAlignment(4);
      this.tNoComptaChapitreCnamPatDebit.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreCnamPatDebit.setHorizontalAlignment(4);
      this.tNoComptaChapitreNet.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreNet.setHorizontalAlignment(4);
      this.tNoComptaChapitreRits.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreRits.setHorizontalAlignment(4);
      this.tNoComptaChapitreRcnss.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreRcnss.setHorizontalAlignment(4);
      this.tNoComptaChapitreRcnam.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tNoComptaChapitreRcnam.setHorizontalAlignment(4);
      this.jLabel65.setFont(new Font("Tahoma", 1, 10));
      this.jLabel65.setText("Chapitre");
      this.jLabel66.setFont(new Font("Tahoma", 1, 10));
      this.jLabel66.setText("Compte");
      this.jLabel67.setFont(new Font("Tahoma", 1, 10));
      this.jLabel67.setText("Cl\u00e9");
      this.tNoComptaCleNet.setToolTipText("");
      this.tNoComptaCleIts.setToolTipText("");
      this.tNoComptaCleCnss.setToolTipText("");
      this.tNoComptaCleCnssMedCredit.setToolTipText("");
      this.tNoComptaCleCnssMedDebit.setToolTipText("");
      this.tNoComptaCleCnssPatCredit.setToolTipText("");
      this.tNoComptaCleCnssPatDebit.setToolTipText("");
      this.tNoComptaCleCnam.setToolTipText("");
      this.tNoComptaCleCnamPatCredit.setToolTipText("");
      this.tNoComptaCleCnamPatDebit.setToolTipText("");
      this.tNoComptaCleRits.setToolTipText("");
      this.tNoComptaCleRcnss.setToolTipText("");
      this.tNoComptaCleRcnam.setToolTipText("");
      GroupLayout jPanel5Layout = new GroupLayout(this.jPanel5);
      this.jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGap(22, 22, 22).addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.jLabel22, -1, -1, 32767).addComponent(this.jLabel23, -1, -1, 32767).addComponent(this.jLabel59, -1, -1, 32767).addComponent(this.jLabel60, -1, -1, 32767).addComponent(this.jLabel25, -1, -1, 32767).addComponent(this.jLabel26, -1, -1, 32767)).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.jLabel62, -1, -1, 32767).addComponent(this.jLabel61, -2, 191, -2)).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.jLabel64, -1, -1, 32767).addComponent(this.jLabel63, -2, 191, -2))).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.jLabel24, -1, -1, 32767).addComponent(this.jLabel50, -1, -1, 32767).addComponent(this.jLabel51, -2, 191, -2))).addPreferredGap(ComponentPlacement.UNRELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.jLabel65, -1, -1, 32767).addComponent(this.tNoComptaChapitreRits).addComponent(this.tNoComptaChapitreRcnss).addComponent(this.tNoComptaChapitreRcnam).addComponent(this.tNoComptaChapitreCnam).addComponent(this.tNoComptaChapitreCnss).addComponent(this.tNoComptaChapitreIts).addComponent(this.tNoComptaChapitreNet).addComponent(this.tNoComptaChapitreCnssMedCredit).addComponent(this.tNoComptaChapitreCnssMedDebit).addComponent(this.tNoComptaChapitreCnssPatCredit).addComponent(this.tNoComptaChapitreCnssPatDebit).addComponent(this.tNoComptaChapitreCnamPatCredit).addComponent(this.tNoComptaChapitreCnamPatDebit, -2, 120, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.tNoComptaRITS, -1, 180, 32767).addComponent(this.tNoComptaRcnss, -1, 180, 32767).addComponent(this.tNoComptaRCNAM, -1, 180, 32767).addComponent(this.tNoComptaCNAM, -1, 180, 32767).addComponent(this.tNoComptaCnss, -1, 180, 32767).addComponent(this.tNoComptaIts, -1, 180, 32767).addComponent(this.tNoComptaNet, -1, 180, 32767).addComponent(this.tNoComptaCnssMedCredit, -1, 180, 32767).addComponent(this.tNoComptaCnssMedDebit, -1, 180, 32767).addComponent(this.tNoComptaCnssPatCredit, -1, 180, 32767).addComponent(this.tNoComptaCnssPatDebit, -1, 180, 32767).addComponent(this.tNoComptaCnamPatCredit, -1, 180, 32767).addComponent(this.tNoComptaCnamPatDebit, -1, 180, 32767).addComponent(this.jLabel66, -1, -1, 32767)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addComponent(this.jLabel67, -2, 50, -2).addComponent(this.tNoComptaCleNet, -2, 57, -2).addComponent(this.tNoComptaCleIts, -2, 57, -2).addComponent(this.tNoComptaCleCnss, -2, 57, -2).addComponent(this.tNoComptaCleCnssMedCredit, -2, 57, -2).addComponent(this.tNoComptaCleCnssMedDebit, -2, 57, -2).addComponent(this.tNoComptaCleCnssPatCredit, -2, 57, -2).addComponent(this.tNoComptaCleCnssPatDebit, -2, 57, -2).addComponent(this.tNoComptaCleCnam, -2, 57, -2).addComponent(this.tNoComptaCleCnamPatCredit, -2, 57, -2).addComponent(this.tNoComptaCleCnamPatDebit, -2, 57, -2).addComponent(this.tNoComptaCleRits, -2, 57, -2).addComponent(this.tNoComptaCleRcnss, -2, 57, -2).addComponent(this.tNoComptaCleRcnam, -2, 57, -2)).addContainerGap(536, 32767)));
      jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup().addGap(40, 40, 40).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel65).addComponent(this.jLabel66).addComponent(this.jLabel67)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tNoComptaChapitreNet, -2, -1, -2).addComponent(this.jLabel26)).addComponent(this.tNoComptaNet, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED, -1, 32767).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel22).addComponent(this.tNoComptaIts, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel23).addComponent(this.tNoComptaCnss, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel59).addComponent(this.tNoComptaCnssMedCredit, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel60).addComponent(this.tNoComptaCnssMedDebit, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel62).addComponent(this.tNoComptaCnssPatCredit, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel61).addComponent(this.tNoComptaCnssPatDebit, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel25).addComponent(this.tNoComptaCNAM, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel64).addComponent(this.tNoComptaCnamPatCredit, -2, -1, -2)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel63).addComponent(this.tNoComptaCnamPatDebit, -2, -1, -2))).addGroup(jPanel5Layout.createSequentialGroup().addComponent(this.tNoComptaChapitreIts, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaChapitreCnss, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaChapitreCnssMedCredit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaChapitreCnssMedDebit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaChapitreCnssPatCredit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaChapitreCnssPatDebit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaChapitreCnam, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaChapitreCnamPatCredit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaChapitreCnamPatDebit, -2, -1, -2))).addGap(10, 10, 10).addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tNoComptaChapitreRits, -2, -1, -2).addComponent(this.jLabel24)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tNoComptaChapitreRcnss, -2, -1, -2).addComponent(this.jLabel50)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tNoComptaChapitreRcnam, -2, -1, -2).addComponent(this.jLabel51))).addGroup(jPanel5Layout.createSequentialGroup().addComponent(this.tNoComptaRITS, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaRcnss, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaRCNAM, -2, -1, -2)))).addGroup(jPanel5Layout.createSequentialGroup().addComponent(this.tNoComptaCleNet, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED, -1, 32767).addComponent(this.tNoComptaCleIts, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleCnss, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleCnssMedCredit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleCnssMedDebit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleCnssPatCredit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleCnssPatDebit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleCnam, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleCnamPatCredit, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleCnamPatDebit, -2, -1, -2).addGap(10, 10, 10).addComponent(this.tNoComptaCleRits, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleRcnss, -2, -1, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tNoComptaCleRcnam, -2, -1, -2))).addGap(63, 63, 63)));
      this.jTabbedPane1.addTab("Comptabilit\u00e9", this.jPanel5);
      this.jPanel8.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Configuration de la semaine ouvrable"));
      this.jLabel16.setFont(new Font("Tahoma", 1, 11));
      this.jLabel16.setText("DIM");
      this.jLabel29.setFont(new Font("Tahoma", 1, 11));
      this.jLabel29.setForeground(new Color(0, 102, 0));
      this.jLabel29.setText("Debut de la semaine");
      this.jLabel34.setFont(new Font("Tahoma", 1, 11));
      this.jLabel34.setForeground(new Color(255, 153, 0));
      this.jLabel34.setText("Fin de la semaine");
      this.jLabel38.setFont(new Font("Tahoma", 1, 11));
      this.jLabel38.setForeground(new Color(204, 0, 0));
      this.jLabel38.setText("Week-end");
      this.jLabel41.setFont(new Font("Tahoma", 1, 11));
      this.jLabel41.setText("LUN");
      this.jLabel42.setFont(new Font("Tahoma", 1, 11));
      this.jLabel42.setText("MAR");
      this.jLabel43.setFont(new Font("Tahoma", 1, 11));
      this.jLabel43.setText("MER");
      this.jLabel44.setFont(new Font("Tahoma", 1, 11));
      this.jLabel44.setText("JEU");
      this.jLabel45.setFont(new Font("Tahoma", 1, 11));
      this.jLabel45.setText("VEN");
      this.jLabel46.setFont(new Font("Tahoma", 1, 11));
      this.jLabel46.setText("SAM");
      GroupLayout jPanel8Layout = new GroupLayout(this.jPanel8);
      this.jPanel8.setLayout(jPanel8Layout);
      jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING, false).addGroup(jPanel8Layout.createSequentialGroup().addContainerGap().addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING, jPanel8Layout.createSequentialGroup().addComponent(this.jLabel34, -2, 131, -2).addGap(105, 105, 105)).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addComponent(this.jLabel29, -2, 131, -2).addComponent(this.jLabel38, -2, 131, -2)).addPreferredGap(ComponentPlacement.RELATED, -1, 32767)))).addGroup(Alignment.LEADING, jPanel8Layout.createSequentialGroup().addGap(169, 169, 169).addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addComponent(this.jLabel16, -2, 32, -2).addComponent(this.cDIMEnd, -2, 20, -2).addComponent(this.cDIMBegin, -2, 20, -2).addComponent(this.cDIMwe, -2, 20, -2)).addPreferredGap(ComponentPlacement.UNRELATED).addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addComponent(this.cLUNEnd, -2, 20, -2).addComponent(this.cLUNBegin, -2, 20, -2).addComponent(this.cLUNwe, -2, 20, -2).addComponent(this.jLabel41, -2, 35, -2)))).addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addComponent(this.jLabel42, -2, 35, -2).addComponent(this.cMAREnd, -2, 20, -2).addComponent(this.cMARBegin, -2, 20, -2).addComponent(this.cMARwe, -2, 20, -2)).addPreferredGap(ComponentPlacement.UNRELATED).addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addComponent(this.jLabel43, -2, 32, -2).addPreferredGap(ComponentPlacement.UNRELATED).addComponent(this.jLabel44, -2, 32, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.jLabel45, -2, 32, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.jLabel46, -2, 32, -2)).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addComponent(this.cMEREnd, -2, 20, -2).addComponent(this.cMERBegin, -2, 20, -2).addComponent(this.cMERwe, -2, 20, -2)).addGap(18, 18, 18).addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addComponent(this.cJEUEnd, -2, 20, -2).addComponent(this.cJEUBegin, -2, 20, -2).addComponent(this.cJEUwe, -2, 20, -2)).addGap(18, 18, 18).addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addComponent(this.cVENEnd, -2, 20, -2).addComponent(this.cVENBegin, -2, 20, -2).addComponent(this.cVENwe, -2, 20, -2)).addGap(18, 18, 18).addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addComponent(this.cSAMEnd, -2, 20, -2).addComponent(this.cSAMBegin, -2, 20, -2).addComponent(this.cSAMwe, -2, 20, -2)))).addContainerGap(659, 32767)));
      jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGap(34, 34, 34).addGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING).addComponent(this.jLabel38).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel16).addComponent(this.jLabel41).addComponent(this.jLabel42).addComponent(this.jLabel43).addComponent(this.jLabel44).addComponent(this.jLabel45).addComponent(this.jLabel46)).addPreferredGap(ComponentPlacement.UNRELATED).addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel8Layout.createSequentialGroup().addGroup(jPanel8Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.jLabel29).addComponent(this.cDIMBegin)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING).addComponent(this.jLabel34).addComponent(this.cDIMEnd)).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cDIMwe)).addGroup(jPanel8Layout.createSequentialGroup().addComponent(this.cLUNBegin).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cLUNEnd).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cLUNwe)).addGroup(jPanel8Layout.createSequentialGroup().addComponent(this.cMARBegin).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cMAREnd).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cMARwe)).addGroup(jPanel8Layout.createSequentialGroup().addComponent(this.cMERBegin).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cMEREnd).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cMERwe)).addGroup(jPanel8Layout.createSequentialGroup().addComponent(this.cJEUBegin).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cJEUEnd).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cJEUwe)).addGroup(jPanel8Layout.createSequentialGroup().addComponent(this.cVENBegin).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cVENEnd).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cVENwe)).addGroup(jPanel8Layout.createSequentialGroup().addComponent(this.cSAMBegin).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cSAMEnd).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.cSAMwe))))).addContainerGap(270, 32767)));
      GroupLayout jPanel4Layout = new GroupLayout(this.jPanel4);
      this.jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING, jPanel4Layout.createSequentialGroup().addContainerGap().addComponent(this.jPanel8, -1, -1, 32767).addContainerGap()));
      jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addComponent(this.jPanel8, -1, -1, 32767).addContainerGap()));
      this.jTabbedPane1.addTab("Heures supp.", this.jPanel4);
      this.jLabel39.setText("Signataires ");
      this.tSignataires.setColumns(20);
      this.tSignataires.setRows(5);
      this.jScrollPane2.setViewportView(this.tSignataires);
      this.jLabel15.setText("Nom respons.");
      this.jLabel18.setText("Qualit\u00e9 resp.");
      GroupLayout jPanel6Layout = new GroupLayout(this.jPanel6);
      this.jPanel6.setLayout(jPanel6Layout);
      jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addContainerGap().addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addComponent(this.jLabel39, -2, 87, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.jScrollPane2, -2, 520, -2)).addGroup(jPanel6Layout.createSequentialGroup().addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING, false).addComponent(this.jLabel15, -1, 87, 32767).addComponent(this.jLabel18, -1, -1, 32767)).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING).addComponent(this.tRespoansable, -2, 342, -2).addComponent(this.tQualiRespo, -2, 342, -2)))).addContainerGap(-1, 32767)));
      jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addGap(30, 30, 30).addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tRespoansable, -2, -1, -2).addComponent(this.jLabel15, -2, 15, -2)).addGap(9, 9, 9).addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE).addComponent(this.tQualiRespo, -2, -1, -2).addComponent(this.jLabel18)).addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel6Layout.createSequentialGroup().addGap(19, 19, 19).addComponent(this.jLabel39)).addGroup(jPanel6Layout.createSequentialGroup().addPreferredGap(ComponentPlacement.UNRELATED).addComponent(this.jScrollPane2, -2, 40, -2))).addContainerGap(304, 32767)));
      this.jTabbedPane1.addTab("Divers", this.jPanel6);
      this.sysRubriqueTable.setModel(new DefaultTableModel(new Object[0][], new String[0]));
      this.sysRubriqueTable.addMouseListener(new 6(this));
      this.jScrollPane7.setViewportView(this.sysRubriqueTable);
      GroupLayout jPanel9Layout = new GroupLayout(this.jPanel9);
      this.jPanel9.setLayout(jPanel9Layout);
      jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING, jPanel9Layout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.jScrollPane7, -2, 1102, -2).addContainerGap()));
      jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(this.jScrollPane7, -2, -1, -2).addContainerGap(33, 32767)));
      this.jTabbedPane1.addTab("SysRubriques", this.jPanel9);
      this.activatePanel.setBorder(BorderFactory.createBevelBorder(0));
      this.tActiveCode.setFont(new Font("Trebuchet MS", 0, 18));
      this.tActiveCode.setHorizontalAlignment(0);
      this.tActiveCode.addKeyListener(new 7(this));
      this.jLabel49.setFont(new Font("Tahoma", 1, 12));
      this.jLabel49.setText("Code d'activation");
      this.lbClientName.setFont(new Font("Tahoma", 1, 12));
      this.lbClientName.setForeground(new Color(0, 153, 0));
      this.lbClientName.setHorizontalAlignment(0);
      this.lbClientName.setText(".");
      this.activateButton.setFont(new Font("Tahoma", 1, 14));
      this.activateButton.setText("Activer");
      this.activateButton.setCursor(new Cursor(0));
      this.activateButton.addActionListener(new 8(this));
      this.CancelActivateButton.setFont(new Font("Tahoma", 1, 14));
      this.CancelActivateButton.setForeground(new Color(255, 0, 0));
      this.CancelActivateButton.setText("D\u00e9sactiver");
      this.CancelActivateButton.setCursor(new Cursor(0));
      this.CancelActivateButton.addActionListener(new 9(this));
      GroupLayout activatePanelLayout = new GroupLayout(this.activatePanel);
      this.activatePanel.setLayout(activatePanelLayout);
      activatePanelLayout.setHorizontalGroup(activatePanelLayout.createParallelGroup(Alignment.LEADING).addGroup(activatePanelLayout.createSequentialGroup().addContainerGap().addGroup(activatePanelLayout.createParallelGroup(Alignment.LEADING).addComponent(this.tActiveCode).addComponent(this.lbClientName, -1, -1, 32767).addGroup(activatePanelLayout.createSequentialGroup().addComponent(this.jLabel49, -2, 119, -2).addGap(0, 0, 32767)).addGroup(activatePanelLayout.createSequentialGroup().addComponent(this.CancelActivateButton, -2, 298, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.activateButton, -1, 781, 32767))).addContainerGap()));
      activatePanelLayout.setVerticalGroup(activatePanelLayout.createParallelGroup(Alignment.LEADING).addGroup(activatePanelLayout.createSequentialGroup().addContainerGap().addComponent(this.jLabel49).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.tActiveCode, -2, 31, -2).addPreferredGap(ComponentPlacement.RELATED).addComponent(this.lbClientName, -2, 27, -2).addPreferredGap(ComponentPlacement.RELATED).addGroup(activatePanelLayout.createParallelGroup(Alignment.BASELINE).addComponent(this.activateButton, -2, 38, -2).addComponent(this.CancelActivateButton, -2, 38, -2)).addGap(32, 32, 32)));
      this.tDateInitLicence.setDateFormatString("dd/MM/yyyy");
      this.tDateInitLicence.setEnabled(false);
      this.tLicencePeriodicity.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0"))));
      this.tLicencePeriodicity.setHorizontalAlignment(4);
      this.tLicencePeriodicity.setEnabled(false);
      this.tDateCurentLicence.setDateFormatString("dd/MM/yyyy");
      this.tDateCurentLicence.setEnabled(false);
      GroupLayout jPanel10Layout = new GroupLayout(this.jPanel10);
      this.jPanel10.setLayout(jPanel10Layout);
      jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING, jPanel10Layout.createSequentialGroup().addGap(23, 23, 23).addComponent(this.activatePanel, -1, -1, 32767).addContainerGap()).addGroup(Alignment.TRAILING, jPanel10Layout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(this.tDateInitLicence, -2, 152, -2).addPreferredGap(ComponentPlacement.RELATED).addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING).addComponent(this.tLicencePeriodicity, Alignment.TRAILING, -2, 63, -2).addGroup(Alignment.TRAILING, jPanel10Layout.createSequentialGroup().addComponent(this.tDateCurentLicence, -2, 152, -2).addGap(75, 75, 75))).addGap(52, 52, 52)));
      jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel10Layout.createSequentialGroup().addGap(45, 45, 45).addComponent(this.activatePanel, -2, -1, -2).addGap(18, 18, 18).addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING).addComponent(this.tDateCurentLicence, Alignment.TRAILING, -2, 25, -2).addComponent(this.tLicencePeriodicity, Alignment.TRAILING, -2, -1, -2).addComponent(this.tDateInitLicence, Alignment.TRAILING, -2, 25, -2)).addContainerGap(187, 32767)));
      this.jTabbedPane1.addTab("Activation", this.jPanel10);
      this.jPanel11.setBackground(new Color(255, 255, 255));
      this.msgErrLabel.setFont(new Font("Segoe UI Light", 0, 12));
      this.msgErrLabel.setForeground(new Color(255, 0, 0));
      this.msgErrLabel.setText("#");
      this.msgErrLabel.setToolTipText("");
      this.lLastUpdate.setFont(new Font("Segoe UI Light", 0, 12));
      this.lLastUpdate.setForeground(new Color(0, 153, 0));
      this.lLastUpdate.setText("#");
      this.lLastUpdate.setToolTipText("");
      this.btnSave.setContentAreaFilled(false);
      this.btnSave.setCursor(new Cursor(0));
      this.btnSave.setOpaque(true);
      this.btnSave.addActionListener(new 10(this));
      GroupLayout jPanel11Layout = new GroupLayout(this.jPanel11);
      this.jPanel11.setLayout(jPanel11Layout);
      jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING, jPanel11Layout.createSequentialGroup().addContainerGap().addComponent(this.msgErrLabel, -2, 619, -2).addPreferredGap(ComponentPlacement.RELATED, -1, 32767).addComponent(this.lLastUpdate, -2, 158, -2).addGap(18, 18, 18).addComponent(this.btnSave, -2, 39, -2).addContainerGap()));
      jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel11Layout.createSequentialGroup().addGap(2, 2, 2).addGroup(jPanel11Layout.createParallelGroup(Alignment.TRAILING).addComponent(this.btnSave, -1, -1, 32767).addComponent(this.msgErrLabel, -1, -1, 32767).addComponent(this.lLastUpdate, -1, -1, 32767)).addGap(2, 2, 2)));
      this.progressBar.setBackground(new Color(204, 204, 204));
      this.progressBar.setForeground(new Color(0, 102, 153));
      this.progressBar.setBorderPainted(false);
      this.progressBar.setOpaque(true);
      this.progressBar.setStringPainted(true);
      GroupLayout layout = new GroupLayout(this.getContentPane());
      this.getContentPane().setLayout(layout);
      layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(this.jPanel1, -1, -1, 32767).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(this.jTabbedPane1, -2, 1151, -2).addContainerGap(-1, 32767)).addComponent(this.jPanel11, Alignment.TRAILING, -1, -1, 32767).addGroup(layout.createSequentialGroup().addComponent(this.progressBar, -2, 1171, -2).addGap(0, 0, 32767)));
      layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(this.jPanel1, -2, -1, -2).addGap(0, 0, 0).addComponent(this.progressBar, -2, -1, -2).addGap(0, 0, 0).addComponent(this.jPanel11, -2, -1, -2).addGap(2, 2, 2).addComponent(this.jTabbedPane1, -2, 490, 32767)));
      this.pack();
   }

   private void photoButtonActionPerformed(ActionEvent var1) {
      JFileChooser chooser = new JFileChooser();
      FileNameExtensionFilter filter = new FileNameExtensionFilter("Fichier image", new String[]{"PNG", "JPG", "JPEG", "BMP", "GIF", "TIFF"});
      chooser.setFileFilter(filter);
      int returnVal = chooser.showOpenDialog(this);
      if (returnVal == 0) {
         this.tLogo.setText(chooser.getSelectedFile().getPath());
         File file = chooser.getSelectedFile();

         try {
            BufferedImage img = ImageIO.read(file);
            ImageIcon icon = new ImageIcon(img);
            Image zoom = GeneralLib.scaleImage(icon.getImage(), 100, 100);
            Icon iconScaled = new ImageIcon(zoom);
            this.tLogoImg.setIcon(iconScaled);
            this.tLogoImg.revalidate();
            this.tLogoImg.repaint();
            this.tLogoDestFile.setText("repport/" + chooser.getSelectedFile().getName());
         } catch (IOException e) {
            this.msgErrLabel.setText(e.getMessage());
         }
      }

   }

   private void sysRubriqueTableMouseClicked(MouseEvent var1) {
   }

   private void tActiveCodeKeyPressed(KeyEvent var1) {
   }

   private void activateButtonActionPerformed(ActionEvent var1) {
      if (this.menu.updateLicence(this.tActiveCode.getText()) == 1) {
         this.tActiveCode.setEnabled(false);
         this.activateButton.setEnabled(false);
         this.CancelActivateButton.setEnabled(true);
         this.menu.showSuccessMsg("Activation reussie! ", 1);
         this.menu.showSuccessMsg("R\u00e9demarrage ELIYA-Paie ...", 1);
         System.exit(0);
      }

   }

   private void showMsg(String var1, int var2) {
      JOptionPane.showMessageDialog(this, msg, "ELIYA-Paie", msgType);
   }

   private void btnSaveActionPerformed(ActionEvent var1) {
      int rep = JOptionPane.showConfirmDialog(this, " Confirmez vous la suavegarde de modifications ?", " Demande de confirmation ", 0);
      if (rep == 0) {
         Thread t = new 11(this);
         t.start();
      }

   }

   private void CancelActivateButtonActionPerformed(ActionEvent var1) {
      int rep = JOptionPane.showConfirmDialog(this, " Confirmez vous l'annulation de l'activation ?", " Demande de confirmation", 0);
      if (rep == 0) {
         Paramgen o = this.menu.paramsGen;
         o.setLicenceKey((String)null);
         o.setNbSalaryCode((String)null);
         o.setNomEntreprise("VERSION DEMO");
         this.menu.gl.updateOcurance(o);
         this.tActiveCode.setText("");
         this.tActiveCode.setEnabled(true);
         this.activateButton.setEnabled(true);
         this.CancelActivateButton.setEnabled(false);
         this.menu.showSuccessMsg("D\u00e9sactivation reusie!", 1);
         this.menu.showSuccessMsg("R\u00e9demarrage ELIYA-Paie ...", 1);
         System.exit(0);
      }

   }

   private void jButton1ActionPerformed(ActionEvent var1) {
      Thread t = new 12(this);
      t.start();
   }

   private void jButton2ActionPerformed(ActionEvent var1) {
      this.tMailSmtpHost.setText("mail.mccmr.com");
      this.tMailUser.setText("no-reply@mccmr.com");
      this.tMailPassword.setText("MC-Consulting@2023");
      this.tMailSmtpPort.setText("25");
      this.cMailSmtpTLSEnabled.setSelected(false);
   }

   private void cRetEngOnCongeActionPerformed(ActionEvent var1) {
   }

   private void btnExitActionPerformed(ActionEvent var1) {
      this.dispose();
   }
}
